M48
; DRILL file {KiCad 7.0.1} date Sat May  6 23:46:42 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-06T23:46:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X192.025Y-161.45
T2
X192.025Y-140.45
T0
M30
